#this script transforms the plain daily csv data generated by pd_listener.sh, to an sql compatible fashion, and avoid lines with false time values
BEGIN{
	#printf("game_id,game_time,user_id,user_name,game_pwin,game_multip,game_roll,game_outcome,game_bet,game_pay\n") #enable if you want a header
	FS=","
}
{
	if(substr($5,1,1)=="<"){
		pwin=substr($5,2)
	}else{
		pwin=(100-substr($5,2))
	}
	if(substr($8,3,1)==":"){	#this line 
	printf("\%d,\%s \%s,\%d,\%s,\%2.2f,\%1.5f,\%2.2f,\%d,\%.8f,\%.8f\n",$4,date,$8,$9,$1,pwin,1/pwin*99,$3,$6,$10,$2);
	}
}
