#this script calculates the walue for the Subseq table
#the imput is generated by the appropriate parts in scripts.sql
BEGIN{
	FS=","
}
{
	if($1==uid){
		print $2, $1, $3-gtime, $4-gbet, gout, gpay
	}
	uid=$1
	gtime=$3
	gbet=$4
	gout=$5
	gpay=$6
}
